sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 19990627
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ***
    access-key-secret: ***
    bucket-name: jonathan-sky-take-out
  redis:
    host: 192.168.46.48
    database: 1
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100 # 连接等待时间
  wechat:
    appid: ***
    secret: ***
